# Generated by Django 6.1.1 on 2026-09-17 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Enter donor's full name", max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Eligible blood donor age is 18 to 65', validators=[django.core.validators.MinValueValidator(18, message='Donor must be at least 18 years old.'), django.core.validators.MaxValueValidator(65, message='Donor age must not exceed 65 years.')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('phone', models.CharField(help_text='Contact number', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 to 15 digits. Example: 9876543210 or +919876543210.', regex='^\\+?[0-9]{10,15}$')])),
                ('email', models.EmailField(help_text='Valid email address', max_length=254)),
                ('city', models.CharField(help_text='Current city', max_length=100)),
                ('address', models.TextField(help_text='Full address details')),
                ('last_donation_date', models.DateField(blank=True, help_text='Last date of blood donation (optional if first time)', null=True)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blood Donor',
                'verbose_name_plural': 'Blood Donors',
                'ordering': ['-created_at'],
            },
        ),
    ]
